{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinylogs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinylogs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinylogs/shinylogs_{{ version }}.tar.gz
  sha256: 75473d9bc6ea931029b274ca3e49ea4b6ceb5ad75b21d4a3c93faf0958e43a03

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-anytime
    - r-bit64
    - r-data.table
    - r-digest
    - r-htmltools
    - r-jsonlite
    - r-nanotime
    - r-shiny >=1.1.0
  run:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-anytime
    - r-bit64
    - r-data.table
    - r-digest
    - r-htmltools
    - r-jsonlite
    - r-nanotime
    - r-shiny >=1.1.0

test:
  commands:
    - $R -e "library('shinylogs')"           # [not win]
    - "\"%R%\" -e \"library('shinylogs')\""  # [win]

about:
  home: https://github.com/dreamRs/shinylogs
  license: GPL-3.0-only
  summary: Track and record the use of applications and the user's interactions with 'Shiny' inputs. Allow to save inputs clicked, output generated and eventually errors.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
